name: GitHub Actions Demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install playwright
      run: pip install pytest-playwright
    
    - name: Install Browsers
      run: playwright install

    - name: Run tests
      run: py.test